name: Bless
main: info.tregmine.chestbless.Bless
version: 1
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info chest protection

commands:
  bless:
    description: bless doors, buttons, plates and chests to specified player.
    -usage: /bless <player>