name: Item
main: info.tregmine.item.Item
version: 3
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info items

commands:
  item:
    description: as admin spawn items
    -usage: /<command> <id|name> <amount> <data>
  give:
    description: as admin spawn items
    -usage: /<command> <id|name> <amount> <data>