name: Invis
main: info.tregmine.invis.Invis
version: 1
author: Ein Andersson
commands:
  vanish:
    description: Toggles your visibility
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players
  poof:
    description: Toggles your visibility
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players