name: Item
main: info.tregmine.item.Item
version: 3
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info items

commands:
  einitem:
    description: spawn items in your inventory.
    -usage: /item <id|name> <amount> <data>
  item:
    description: spawn items in your inventory.
    -usage: /item <id|name> <amount> <data>
  give:
    description: spawn items in a specified player's inventory. 
    -usage: /give <player> <id|name> <amount>