name: Basic Commands
main: info.tregmine.basiccommands.BasicCommands
version: 50
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info items

commands:
  pos:
    description: gives you your current position
    -usage: /<command>
  nuke:
    description: kills all mobs in the current world
    -usage: /<command>
  kick:
    description: kick someone from the server
    -usage: /<command>
  ban:
    description: ban someone from the server
    -usage: /<command>
  killp:
    description: to kill some one
    -usage: /<command>
  clean:
    description: clear your inventory
    -usage: /<command>
  createmob:
    description: spawn mobs
    -usage: /<command>
  sendto:
    description: spawn mobs
    -usage: /<command>
  user:
    description: spawn mobs
    -usage: /<command>    
  test:
    description: spawn mobs
    -usage: /<command>    
  killstreak:
    description: spawn mobs
    -usage: /<command>    
  newspawn:
    description: spawn mobs
    -usage: /<command>
  time:
    description: spawn mobs
    -usage: /<command>
  lagtest:
    description: spawn mobs
    -usage: /<command>
  ride.:
    description: spawn mobs
    -usage: /<command>        
  eject:
    description: spawn mobs
    -usage: /<command>
  w:
    description: spawn mobs
    -usage: /<command>
  stopmsg:
    description: spawn mobs
    -usage: /<command>
  tpblock:
    description: spawn mobs
    -usage: /<command>
  removeadmin:
    description: spawn mobs
    -usage: /<command>
  removebuilder:
    description: spawn mobs
    -usage: /<command>
  password:
    description: spawn mobs
    -usage: /<command>
  time:
    description: spawn mobs
    -usage: /<command>
  t:
    description: spawn mobs
    -usage: /<command>
  td:
    description: spawn mobs
    -usage: /<command>
  admin:
    description: spawn mobs
    -usage: /<command>