name: Basic Commands
main: info.tregmine.basiccommands.BasicCommands
version: 50
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info items

commands:
  pos:
    description: retrieve information about your current position.
    -usage: /pos
  nuke:
    description: kill all hostile mobs in the current world.
    -usage: /nuke
  kick:
    description: kick specified player from the server.
    -usage: /kick <player>
  ban:
    description: ban specified player from the server.
    -usage: /ban <player>
  killp:
    description: kill specified player.
    -usage: /killp <player>
  clean:
    description: erase your inventory and toolbar.
    -usage: /clean
  createmob:
    description: spawn mobs.
    -usage: /createmob
  sendto:
    description: spawn mobs
    -usage: /<command>
  user:
    description: spawn mobs
    -usage: /<command>    
  test:
    description: spawn mobs
    -usage: /<command>    
  killstreak:
    description: spawn mobs
    -usage: /<command>    
  newspawn:
    description: spawn mobs
    -usage: /<command>
  time:
    description: spawn mobs
    -usage: /<command>
  lagtest:
    description: spawn mobs
    -usage: /<command>
  ride.:
    description: ride on specified player's shoulders.
    -usage: /ride <player>        
  eject:
    description: stop riding on specified player's shoulders.
    -usage: eject <player>
  w:
    description: spawn mobs
    -usage: /<command>
  stopmsg:
    description: kick everyone off the server
    -usage: /<command>
  tpblock:
    description: prevent people from teleporting to you.
    -usage: /tpblock true/false/info
  normal:
    description: removes your special permissions until you relog.
    -usage: /normal
  password:
    description: change your password
    -usage: /password <oldp password> <new password>
  time:
    description: change your world time. This only affects you.
    -usage: /time day/night/normal
  t:
    description: hit specified player with lightning.
    -usage: /t <player>
  td:
    description: hit and kill specified player with lightning.
    -usage: /td <player>
  creative:
    description: enter creative mode
    -usage: /admin
  survival:
    description: enter survival mode
    -usage: /survival
  cname:
    description: change your nickname and its color.
    -usage: /cname color nick
