name: Fill
main: info.tregmine.boxfill.BoxFill
version: 23
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info items

commands:
  fill:
    description: fill a cube with specified blocks. You can also convert specified blocks to another kind of block. You can copy a section and paste it elsewhere. Fill undo undos the latest fill. Select the diagonal corners with the wood spade.
    -usage: /fill <id:type> <new-id:new-type> \
    /fill copy \
    /fill paste <degrees> \
    /fill undo
  testfill:
    description: make a faux fill. Only you will see it and it will be gone when you relog.
    -usage: /testfill <id:type> <new-id:new-type>
  crestore:
    description: restore a chunk to its original look. Right click once with the wood spade inside the chunk.
    -usage: /crestore
  timemachine:
    description: undo specified player's last block actions.
    -usage: /timemachine <player>
  blockhere:
    description: place a block under your feet.
    -usage: /blockhere
  timerestore:
    description: restore missing blocks in case of rollback.
    -usage: /timerestore