name: Spy
main: info.tregmine.inventoryspy.Main
version: 1
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info Currency

commands:
  inv:
    description: wallet commands
    -usage: /<command>