name: Spy
main: info.tregmine.inventoryspy.Main
version: 1
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info Currency

commands:
  inv:
    description: browse specified player's inventory. You must stand close to them.
    -usage: /inv <player>
  safetrade:
    description: browse specified player's inventory. You must stand close to them.
    -usage: /inv <player>