name: Teleport
main: info.tregmine.teleport.Teleport
version: 60

website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info teleportation

commands:
  tp:
    description: teleport to specified player.
    -usage: /tp <player>
  tpto:
    description: teleport to a location.
    -usage: /tpto <x> <y> <z>
  spawn:
    description: teleport to the spawn location.
    -usage: /spawn
  s:
    description: summon specified player.
    -usage: /s <player>
  warp:
    description: teleport to specified warp.
    -usage: /warp <warpname>
  home:
    description: teleport to your home. You can set home with /home save.
    -usage: /home (save)
  alpha:
    description: teleport to the alpha world.
    -usage: /alpha
  skyland:
    description: teleport to the skyland world.
    -usage: /skyland