name: Teleport
main: info.tregmine.teleport.Teleport
version: 60

website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info teleportation

commands:
  tp:
    description: Teleport tp another player
    -usage: /<command> <player>
  tpto:
    description: Teleport tp another player
    -usage: /<command> <player>
  spawn:
    description: sends you back to where you started
    -usage: /<command> <player>|list
  s:
    description: summon someone to you
    -usage: /<command> <player>
  warp:
    description: send you to a warp
    -usage: /<command> <warpname>
  home:
    description: send you to a warp
    -usage: /<command> <warpname>    
  alpha:
    description: send you to a warp
    -usage: /<command> <warpname>
  childsplay:
    description: send you to a warp
    -usage: /<command> <warpname>
  skyland:
    description: send you to a warp
    -usage: /<command> <warpname>
  matrix:
    description: send you to a warp
    -usage: /<command> <warpname>
    