enabled: false
general:
  motd:
    lineone: "#r< #6Descriptor #r> < #c First Line #r >"
    #Line two will always be used, line one will only be used if lineoneauto is set to false.
    linetwo: "#r< #6Second Line #r>"
    maxplayers: 64
  servername: Server
  afk:
    #In seconds
    autoafk: 300
  economy:
    #Disable to use the /sell command instead
    minefortregs: true
  url: https://www.tregmine.com
api:
  signing-key: secure-hash-here
  port: 9192
db:
  url: jdbc:mysql://localhost:3306/tregmine_db?autoReconnect=true
  user: tregmine_db
  password: secure-password-here
support:
  user: tregmine.mc@gmail.com
  password: yourpasswordherelolgtgbye
  to:
    - hey@420.net
worlds:
  enabled: false
  vanillaworld: false
  # This is a list of strings for extra worlds to be generated.
  # Strings containing _the_end will generate end-style worlds.
  # Strings containing _nether will generate nether-style worlds.
  names:
  special:
    # Before setting to true, move world to world_2 as with the nether and end
    newworld: true
    restrictnewworldtostaff: true
#Rank Chat Colors
ranks:
  colors:
    tourist: "#f"
    settler: "#a"
    resident: "#2"
    donator: "#6"
    guardian: "#9"
    coder: "#5"
    builder: "#e"
    junior: "#c"
    senior: "#4"
discord-bot:
  enabled: false
  token: "your-token-here"
  guild:
    guild-id: "guild-id"
    chat-channel-id: "channel-id"
  status: "mc.tregmine.com"
  behavior:
    startup:
      enabled: true
      message: "Tregmine is online!"
    embed-footer: "Made by TregBot XOXO"