name: Chat
main: info.tregmine.chat.Chat
version: 51

website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info items

commands:
  me:
    description: prints "* <yournick> <specified text>".
    -usage: /me <text> 
  msg:
    description: send a private message to someone.
    -usage: /msg <name> <text> 
  m:
    description: send a private message to someone.
    -usage: /msg <name> <text> 
  tell:
    description: send a private message to someone.
    -usage: /msg <name> <text> 
  god:
    description: talk as the red God.
    -usage: /god <text>
  facepalm: prints "<yournick> * facepalm *"
    description: sends a private message to someone.
    -usage: /facepalm
  say:
    description: talk as god with your individual color. If you don't have one you will talk as red god.
    -usage: /say text
  force:
    description: force someone into a channel.
    -usage: /force <nickname> <channel name>    
  channel:
    description: enter a channel.
    -usage: /channel <channel name>
    