name: Tregmine
main: info.tregmine.Tregmine
version: 2014
website: http://tregmine.info
author: Ein Andersson
description: Tregmine

commands:
  who:
    description: show a list of who is online.
    -usage: /who
  tp:
    description: teleport to specified player.
    -usage: /tp <player>
  channel:
    description: Join a chat channel
    -usage: /channel channelname
    