name: Tregmine
main: info.tregmine.Tregmine
version: 4010
website: http://tregmine.info
author: Ein Andersson
description: Tregmine

commands:
  head:
    description: show a list of who is online.
    -usage: /who
  who:
    description: show a list of who is online.
    -usage: /who
  tp:
    description: teleport to specified player.
    -usage: /tp <player>
  channel:
    description: Join a chat channel
    -usage: /channel channelname
  force:
    description: Join a chat channel
    -usage: /channel channelname
  m:
    description: send a private message
    -usage: /m <player> message
  msg:
    description: send a private message
    -usage: /m <player> message
  tell:
    description: send a private message
    -usage: /m <player> message
  me:
    description: send a private message
    -usage: /m <player> message
  say:
    description: talk as good
    -usage: /say message
        