name: Tregmine
main: info.tregmine.Tregmine
version: 20.01.00.01
website: http://tregmine.info
author: Ein Andersson
description: Tregmine
depend: [Zones, Votifier, Currency]

commands:
  blackout:
    description: unknown
    -usage: /unkown
  book:
    description: unknown
    -usage: /unkown
  te:
    description: unknown
    -usage: /unkown
  settler:
    description: unknown
    -usage: /unkown
  donator:
    description: unknown
    -usage: /unkown
  op:
    description: unknown
    -usage: /unkown
  invis:
    description: unknown
    -usage: /unkown
  text:
    description: unknown
    -usage: /unkown
  head:
    description: show a list of who is online.
    -usage: /who
  who:
    description: show a list of who is online.
    -usage: /who
  tp:
    description: teleport to specified player.
    -usage: /tp <player>
  channel:
    description: Join a chat channel
    -usage: /channel channelname
  force:
    description: Join a chat channel
    -usage: /channel channelname
  m:
    description: send a private message
    -usage: /m <player> message
  msg:
    description: send a private message
    -usage: /m <player> message
  tell:
    description: send a private message
    -usage: /m <player> message
  me:
    description: send a private message
    -usage: /m <player> message
  say:
    description: talk as good
    -usage: /say message
        