name: Zones
main: info.tregmine.zones.ZonesPlugin
version: 15
website: http://tregmine.info
author: Ein Andersson and Emil Hernvall
description: Tregmine.info Zones

commands:
  zone:
    description: manipulate zones
    -usage: /zone [command]
  town:
    description: synonym for /zone
    -usage: /town [command]
  lot:
    description: manipulate lots
    -usage: /lot [command]

