name: Currency
main: info.tregmine.currency.Main
version: 33
website: http://tregmine.info
author: Ein Andersson
description: Tregmine.info Currency

commands:
  wallet:
    description: allows you to handle your wallet. You can check your balance, show your balance to others and send a specified amount to players.
    -usage: /wallet give <player> <amount> \
    /wallet tell \
    /wallet balance